name: Using classic charts
uses: lowlighter/metrics@latest
with:
  filename: metrics.plugin.stargazers.svg
  token: ${{ secrets.METRICS_TOKEN }}
  base: ""
  plugin_stargazers: yes
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
